# PostgreSQL dev profile
spring.datasource.url=jdbc:postgresql://localhost:5432/surveylion
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
